pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo hello world!'
            }
        }
        stage('Test') {
            steps {
                sh 'echo hello again1'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo hello again2'
            }
        }
    }
}
